version: '3.9'

services:
  ps_db:
    container_name: ps_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    ports:
      - '5432:5432'
    volumes:
      - ps_data:/var/lib/postgresql/data/

  api:
    build: .
    container_name: fast_api
    restart: unless-stopped
    tty: true
    volumes:
      - .:/backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - ps_db

volumes:
  ps_data:
